export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';

export const TEST_UPDATE_ANSWERS = 'TEST_UPDATE_ANSWERS';
export const TEST_ERROR = 'TEST_ERROR';
export const TEST_LOADING = 'TEST_LOADING';
export const TEST_SET = 'TEST_SET';
export const TEST_TAKEN = 'TEST_TAKEN';
export const TEST_FINISHED_ID = 'TEST_FINISHED_ID';

export const TEST_INFO = 'TEST_INFO';
export const TEST_INFO_ERROR = 'TEST_INFO_ERROR';
export const TEST_INFO_LOADING = 'TEST_INFO_LOADING';
export const TEST_INFO_LIST = 'TEST_INFO_LIST';
export const TEST_INFO_LIST_ERROR = 'TEST_INFO_LIST_ERROR';
export const TEST_INFO_LIST_LOADING = 'TEST_INFO_LIST_LOADING';

export const TEST_SCORE = 'TEST_SCORE';
export const TEST_SCORE_ERROR = 'TEST_SCORE_ERROR';
export const TEST_SCORE_LOADING = 'TEST_SCORE_LOADING';
export const TEST_SCORE_LIST = 'TEST_SCORE_LIST';
export const TEST_SCORE_LIST_ERROR = 'TEST_SCORE_LIST_ERROR';
export const TEST_SCORE_LIST_LOADING = 'TEST_SCORE_LIST_LOADING';


